export default {
	LOADING: 'LOADING',
	SHOWINTRO: 'SHOWINTRO',
	LANGUAGECODE: 'LANGUAGECODE',
	SHOWMODAL: 'SHOWMODAL',
	RESETSTATE: 'RESETSTATE',


	BUKHARILIST: 'BUKHARILIST',
	BUKHARIDETAILS: 'BUKHARIDETAILS',
	QURANLIST: 'QURANLIST',
	QURANDETAILS: 'QURANDETAILS'
	// SIGNUP : 'SIGNUP',
	// SIGNIN : 'SIGNIN',
	// LOGOUT : 'LOGOUT',
	// FORGOTPASSWORD : 'FORGOTPASSWORD',

};